In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('nutrition.csv')

In [4]:
df.head()

,Unnamed: 0,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [22]:
data = df[['name', 'calories', 'total_fat', 'protein', 'carbohydrate']]

In [13]:
data = pd.DataFrame()
data['name'] = df['name'].str.lower()
data['calories'] = df['calories'].astype(int)
data['fats'] = df['total_fat'].str.replace(r'[^\d.]', '', regex=True).astype(float)
data['proteins'] = df['protein'].str.replace(r'[^\d.]', '', regex=True).astype(float)
data['carbohydrates'] = df['carbohydrate'].str.replace(r'[^\d.]', '', regex=True).astype(float)

In [14]:
data.head()

              name  calories  fats  proteins  carbohydrates
0       cornstarch       381   0.1      0.26          91.27
1     nuts, pecans       691  72.0      9.17          13.86
2    eggplant, raw        25   0.2      0.98           5.88
3   teff, uncooked       367   2.4     13.30          73.13
4  sherbet, orange       144   2.0      1.10          30.40

In [35]:
 data['name']=data['name'].str.lower()

/var/folders/kq/dmy4ffs56xj_0h72qcbpyf400000gn/T/ipykernel_69770/966699872.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['name']=data['name'].str.lower()

In [10]:
dataset = data.set_index('name')

In [12]:
dataset = dataset.str.lower()

AttributeError: 'DataFrame' object has no attribute 'str'

In [11]:
dataset.to_dict('index')

{'Cornstarch': {'calories': 381,
  'fats': 0.1,
  'proteins': 0.26,
  'carbohydrates': 91.27},
 'Nuts, pecans': {'calories': 691,
  'fats': 72.0,
  'proteins': 9.17,
  'carbohydrates': 13.86},
 'Eggplant, raw': {'calories': 25,
  'fats': 0.2,
  'proteins': 0.98,
  'carbohydrates': 5.88},
 'Teff, uncooked': {'calories': 367,
  'fats': 2.4,
  'proteins': 13.3,
  'carbohydrates': 73.13},
 'Sherbet, orange': {'calories': 144,
  'fats': 2.0,
  'proteins': 1.1,
  'carbohydrates': 30.4},
 'Cauliflower, raw': {'calories': 25,
  'fats': 0.3,
  'proteins': 1.92,
  'carbohydrates': 4.97},
 'Taro leaves, raw': {'calories': 42,
  'fats': 0.7,
  'proteins': 4.98,
  'carbohydrates': 6.7},
 'Lamb, raw, ground': {'calories': 282,
  'fats': 23.0,
  'proteins': 16.56,
  'carbohydrates': 0.0},
 'Cheese, camembert': {'calories': 300,
  'fats': 24.0,
  'proteins': 19.8,
  'carbohydrates': 0.46},
 'Vegetarian fillets': {'calories': 290,
  'fats': 18.0,
  'proteins': 23.0,
  'carbohydrates': 9.0},
 'PACE, Picante Sauce': {'calories': 25,
  'fats': 0.0,
  'proteins': 0.0,
  'carbohydrates': 6.25},
 'Goji berries, dried': {'calories': 349,
  'fats': 0.4,
  'proteins': 14.26,
  'carbohydrates': 77.06},
 'Mango nectar, canned': {'calories': 51,
  'fats': 0.1,
  'proteins': 0.11,
  'carbohydrates': 13.12},
 'Crackers, rusk toast': {'calories': 407,
  'fats': 7.2,
  'proteins': 13.5,
  'carbohydrates': 72.3},
 'Chicken, boiled, feet': {'calories': 215,
  'fats': 15.0,
  'proteins': 19.4,
  'carbohydrates': 0.2},
 'Quail, raw, meat only': {'calories': 134,
  'fats': 4.5,
  'proteins': 21.76,
  'carbohydrates': 0.0},
 'Pie, lemon, fried pies': {'calories': 316,
  'fats': 16.0,
  'proteins': 3.0,
  'carbohydrates': 42.6},
 'Peppers, raw, jalapeno': {'calories': 29,
  'fats': 0.4,
  'proteins': 0.91,
  'carbohydrates': 6.5},
 'Winged bean tuber, raw': {'calories': 148,
  'fats': 0.9,
  'proteins': 11.6,
  'carbohydrates': 28.1},
 'Salami, turkey, cooked': {'calories': 172,
  'fats': 9.2,
  'proteins': 19.2,
  'carbohydrates': 1.55},
 'Grapes, raw, muscadine': {'calories': 57,
  'fats': 0.5,
  'proteins': 0.81,
  'carbohydrates': 13.93},
 'Nuts, raw, ginkgo nuts': {'calories': 182,
  'fats': 1.7,
  'proteins': 4.32,
  'carbohydrates': 37.6},
 'Spices, ground, savory': {'calories': 272,
  'fats': 5.9,
  'proteins': 6.73,
  'carbohydrates': 68.73},
 'Candies, sesame crunch': {'calories': 516,
  'fats': 33.0,
  'proteins': 11.6,
  'carbohydrates': 50.3},
 'Cheese, low fat, cream': {'calories': 201,
  'fats': 15.0,
  'proteins': 7.85,
  'carbohydrates': 8.13},
 'PACE, Green Taco Sauce': {'calories': 25,
  'fats': 0.0,
  'proteins': 0.0,
  'carbohydrates': 6.25},
 'Syrup, Canadian, maple': {'calories': 270,
  'fats': 0.0,
  'proteins': 0.0,
  'carbohydrates': 67.38},
 'Ostrich, raw, top loin': {'calories': 119,
  'fats': 3.0,
  'proteins': 21.67,
  'carbohydrates': 0.0},
 'Chewing gum, sugarless': {'calories': 268,
  'fats': 0.4,
  'proteins': 0.0,
  'carbohydrates': 94.8},
 'Nuts, dried, pine nuts': {'calories': 673,
  'fats': 68.0,
  'proteins': 13.69,
  'carbohydrates': 13.08},
 'Pasta, unenriched, dry': {'calories': 371,
  'fats': 1.5,
  'proteins': 13.04,
  'carbohydrates': 74.67},
 "McDONALD'S, Side Salad": {'calories': 20,
  'fats': 0.2,
  'proteins': 1.03,
  'carbohydrates': 4.3},
 'Cookies, Marie biscuit': {'calories': 406,
  'fats': 11.0,
  'proteins': 7.05,
  'carbohydrates': 70.54},
 'Broccoli, raw, chinese': {'calories': 30,
  'fats': 0.8,
  'proteins': 1.2,
  'carbohydrates': 4.67},
 "McDONALD'S, Hash Brown": {'calories': 271,
  'fats': 16.0,
  'proteins': 2.48,
  'carbohydrates': 28.56},
 'Agave, raw (Southwest)': {'calories': 68,
  'fats': 0.2,
  'proteins': 0.52,
  'carbohydrates': 16.23},
 'Emu, raw, outside drum': {'calories': 103,
  'fats': 0.5,
  'proteins': 23.08,
  'carbohydrates': 0.0},
 'Nuts, dried, beechnuts': {'calories': 576,
  'fats': 50.0,
  'proteins': 6.2,
  'carbohydrates': 33.5},
 'Currants, dried, zante': {'calories': 283,
  'fats': 0.3,
  'proteins': 4.08,
  'carbohydrates': 74.08},
 'Lentils, raw, sprouted': {'calories': 106,
  'fats': 0.6,
  'proteins': 8.96,
  'carbohydrates': 22.14},
 'Gravy, mix, dry, onion': {'calories': 322,
  'fats': 3.0,
  'proteins': 9.0,
  'carbohydrates': 67.64},
 'Pie, fruit, fried pies': {'calories': 316,
  'fats': 16.0,
  'proteins': 3.0,
  'carbohydrates': 42.6},
 'Snacks, cakes, popcorn': {'calories': 384,
  'fats': 3.1,
  'proteins': 9.7,
  'carbohydrates': 80.1},
 'Snack, Mixed Berry Bar': {'calories': 383,
  'fats': 11.0,
  'proteins': 13.16,
  'carbohydrates': 58.84},
 'Fish, raw, sheepshead': {'calories': 108,
  'fats': 2.4,
  'proteins': 20.21,
  'carbohydrates': 0.0},
 'Babyfood, pear, juice': {'calories': 47,
  'fats': 0.0,
  'proteins': 0.0,
  'carbohydrates': 11.86},
 'Brussels sprouts, raw': {'calories': 43,
  'fats': 0.3,
  'proteins': 3.38,
  'carbohydrates': 8.95},
 'Broccoli raab, cooked': {'calories': 33,
  'fats': 0.5,
  'proteins': 3.83,
  'carbohydrates': 3.12},
 'Butter oil, anhydrous': {'calories': 876,
  'fats': 99.0,
  'proteins': 0.28,
  'carbohydrates': 0.0},
 'Chicory, raw, witloof': {'calories': 17,
  'fats': 0.1,
  'proteins': 0.9,
  'carbohydrates': 4.0},
 'KEEBLER, Waffle Cones': {'calories': 424,
  'fats': 5.3,
  'proteins': 6.5,
  'carbohydrates': 87.7},
 'KEEBLER, Waffle Bowls': {'calories': 424,
  'fats': 5.3,
  'proteins': 6.5,
  'carbohydrates': 87.7},
 'Broccoli, raw, leaves': {'calories': 28,
  'fats': 0.4,
  'proteins': 2.98,
  'carbohydrates': 5.06},
 'Durian, raw or frozen': {'calories': 147,
  'fats': 5.3,
  'proteins': 1.47,
  'carbohydrates': 27.09},
 'Tomatoes, raw, orange': {'calories': 16,
  'fats': 0.2,
  'proteins': 1.16,
  'carbohydrates': 3.18},
 'Tomatoes, raw, yellow': {'calories': 15,
  'fats': 0.3,
  'proteins': 0.98,
  'carbohydrates': 2.98},
 'Egg custards, dry mix': {'calories': 410,
  'fats': 6.4,
  'proteins': 6.9,
  'carbohydrates': 82.8},
 'Peanut flour, low fat': {'calories': 428,
  'fats': 22.0,
  'proteins': 33.8,
  'carbohydrates': 31.27},
 'Fish, smoked, haddock': {'calories': 116,
  'fats': 1.0,
  'proteins': 25.23,
  'carbohydrates': 0.0},
 "DENNY'S, french fries": {'calories': 282,
  'fats': 14.0,
  'proteins': 3.41,
  'carbohydrates': 35.2},
 'Ground turkey, cooked': {'calories': 203,
  'fats': 10.0,
  'proteins': 27.37,
  'carbohydrates': 0.0},
 'MURRAY, Vanilla Wafer': {'calories': 461,
  'fats': 17.0,
  'proteins': 4.0,
  'carbohydrates': 72.9},
 "WENDY'S, french fries": {'calories': 301,
  'fats': 14.0,
  'proteins': 3.73,
  'carbohydrates': 39.73},
 'Bread, toasted, wheat': {'calories': 313,
  'fats': 4.3,
  'proteins': 12.96,
  'carbohydrates': 55.77},
 'Danish pastry, cheese': {'calories': 374,
  'fats': 22.0,
  'proteins': 8.0,
  'carbohydrates': 37.2},
 'Nuts, glazed, walnuts': {'calories': 500,
  'fats': 36.0,
  'proteins': 8.28,
  'carbohydrates': 47.59},
 'Spices, garlic powder': {'calories': 331,
  'fats': 0.7,
  'proteins': 16.55,
  'carbohydrates': 72.73},
 'Oil, soybean lecithin': {'calories': 763,
  'fats': 100.0,
  'proteins': 0.0,
  'carbohydrates': 0.0},
 'Egg, fresh, raw, yolk': {'calories': 322,
  'fats': 27.0,
  'proteins': 15.86,
  'carbohydrates': 3.59},
 'Fireweed, raw, leaves': {'calories': 103,
  'fats': 2.8,
  'proteins': 4.71,
  'carbohydrates': 19.22},
 'Beef, pastrami, cured': {'calories': 147,
  'fats': 5.8,
  'proteins': 21.8,
  'carbohydrates': 0.36},
 'Frankfurter, meatless': {'calories': 233,
  'fats': 14.0,
  'proteins': 19.61,
  'carbohydrates': 7.7},
 'Emu, raw, flat fillet': {'calories': 102,
  'fats': 0.7,
  'proteins': 22.25,
  'carbohydrates': 0.0},
 'Emu, raw, inside drum': {'calories': 108,
  'fats': 1.5,
  'proteins': 22.22,
  'carbohydrates': 0.0},
 'Ice creams, chocolate': {'calories': 216,
  'fats': 11.0,
  'proteins': 3.8,
  'carbohydrates': 28.2},
 'Snacks, potato sticks': {'calories': 522,
  'fats': 34.0,
  'proteins': 6.7,
  'carbohydrates': 53.3},
 'USDA Commodity, salsa': {'calories': 36,
  'fats': 0.2,
  'proteins': 1.5,
  'carbohydrates': 7.0},
 'Figs, uncooked, dried': {'calories': 249,
  'fats': 0.9,
  'proteins': 3.3,
  'carbohydrates': 63.87},
 'Game meat, raw, horse': {'calories': 133,
  'fats': 4.6,
  'proteins': 21.39,
  'carbohydrates': 0.0},
 'Syrup, fruit flavored': {'calories': 261,
  'fats': 0.0,
  'proteins': 0.0,
  'carbohydrates': 65.1},
 'Broccoli, raw, stalks': {'calories': 28,
  'fats': 0.4,
  'proteins': 2.98,
  'carbohydrates': 5.24},
 'Cream, cultured, sour': {'calories': 198,
  'fats': 19.0,
  'proteins': 2.44,
  'carbohydrates': 4.63},
 'Gravy, canned, au jus': {'calories': 16,
  'fats': 0.2,
  'proteins': 1.2,
  'carbohydrates': 2.5},
 "McDONALD'S, Hamburger": {'calories': 264,
  'fats': 10.0,
  'proteins': 12.92,
  'carbohydrates': 30.28},
 'Cheese, port de salut': {'calories': 352,
  'fats': 28.0,
  'proteins': 23.78,
  'carbohydrates': 0.57},
 'SILK Original Creamer': {'calories': 100,
  'fats': 6.7,
  'proteins': 0.0,
  'carbohydrates': 6.67},
 'SILK Hazelnut Creamer': {'calories': 133,
  'fats': 6.7,
  'proteins': 0.0,
  'carbohydrates': 20.0},
 'Soup, mix, dry, onion': {'calories': 293,
  'fats': 0.3,
  'proteins': 7.48,
  'carbohydrates': 65.07},
 'Mushrooms, raw, enoki': {'calories': 37,
  'fats': 0.3,
  'proteins': 2.66,
  'carbohydrates': 7.81},
 'Bacon and beef sticks': {'calories': 517,
  'fats': 44.0,
  'proteins': 29.1,
  'carbohydrates': 0.8},
 'Salami, pork, Italian': {'calories': 425,
  'fats': 37.0,
  'proteins': 21.7,
  'carbohydrates': 1.2},
 'Crackers, whole-wheat': {'calories': 427,
  'fats': 14.0,
  'proteins': 10.58,
  'carbohydrates': 69.55},
 'Peanuts, raw, spanish': {'calories': 570,
  'fats': 50.0,
  'proteins': 26.15,
  'carbohydrates': 15.83},
 'Hominy, white, canned': {'calories': 72,
  'fats': 0.9,
  'proteins': 1.48,
  'carbohydrates': 14.26},
 'Game meat, raw, moose': {'calories': 102,
  'fats': 0.7,
  'proteins': 22.24,
  'carbohydrates': 0.0},
 'Pears, red anjou, raw': {'calories': 62,
  'fats': 0.1,
  'proteins': 0.33,
  'carbohydrates': 14.94},
 'Horseradish, prepared': {'calories': 48,
  'fats': 0.7,
  'proteins': 1.18,
  'carbohydrates': 11.29},
 'Fish, raw, butterfish': {'calories': 146,
  'fats': 8.0,
  'proteins': 17.28,
  'carbohydrates': 0.0},
 'Lebanon bologna, beef': {'calories': 172,
  'fats': 10.0,
  'proteins': 19.03,
  'carbohydrates': 0.44},
 'Ham and cheese spread': {'calories': 245,
  'fats': 19.0,
  'proteins': 16.18,
  'carbohydrates': 2.28},
 'TACO BELL, Taco Salad': {'calories': 170,
  'fats': 9.2,
  'proteins': 6.69,
  'carbohydrates': 15.1},
 'Sauce, worcestershire': {'calories': 78,
  'fats': 0.0,
  'proteins': 0.0,
  'carbohydrates': 19.46},
 'Candies, marshmallows': {'calories': 318,
  'fats': 0.2,
  'proteins': 1.8,
  'carbohydrates': 81.3},
 'Hummus, home prepared': {'calories': 177,
  'fats': 8.6,
  'proteins': 4.86,
  'carbohydrates': 20.12},
 'Horned melon (Kiwano)': {'calories': 44,
  'fats': 1.3,
  'proteins': 1.78,
  'carbohydrates': 7.56},
 'Ice cream sundae cone': {'calories': 254,
  'fats': 14.0,
  'proteins': 3.0,
  'carbohydrates': 28.89},
 'Peppers, raw, serrano': {'calories': 32,
  'fats': 0.4,
  'proteins': 1.74,
  'carbohydrates': 6.7},
 'Cabbage, cooked, napa': {'calories': 12,
  'fats': 0.2,
  'proteins': 1.1,
  'carbohydrates': 2.23},
 'Peppers, dried, ancho': {'calories': 281,
  'fats': 8.2,
  'proteins': 11.86,
  'carbohydrates': 51.42},
 'Parsley, freeze-dried': {'calories': 271,
  'fats': 5.2,
  'proteins': 31.3,
  'carbohydrates': 42.38},
 'Spices, black, pepper': {'calories': 251,
  'fats': 3.3,
  'proteins': 10.39,
  'carbohydrates': 63.95},
 'Spices, white, pepper': {'calories': 296,
  'fats': 2.1,
  'proteins': 10.4,
  'carbohydrates': 68.61},
 'Yambean (jicama), raw': {'calories': 38,
  'fats': 0.1,
  'proteins': 0.72,
  'carbohydrates': 8.82},
 'Nuts, dried, pilinuts': {'calories': 719,
  'fats': 80.0,
  'proteins': 10.8,
  'carbohydrates': 3.98},
 'Kiwifruit, raw, green': {'calories': 61,
  'fats': 0.5,
  'proteins': 1.14,
  'carbohydrates': 14.66},
 'Drumstick leaves, raw': {'calories': 64,
  'fats': 1.4,
  'proteins': 9.4,
  'carbohydrates': 8.28},
 'Yautia (tannier), raw': {'calories': 98,
  'fats': 0.4,
  'proteins': 1.46,
  'carbohydrates': 23.63},
 'Candies, butterscotch': {'calories': 391,
  'fats': 3.3,
  'proteins': 0.03,
  'carbohydrates': 90.4},
 'Cucumber, raw, peeled': {'calories': 12,
  'fats': 0.2,
  'proteins': 0.59,
  'carbohydrates': 2.16},
 'Dandelion greens, raw': {'calories': 45,
  'fats': 0.7,
  'proteins': 2.7,
  'carbohydrates': 9.2},
 'Melons, raw, honeydew': {'calories': 36,
  'fats': 0.1,
  'proteins': 0.54,
  'carbohydrates': 9.09},
 'Potato salad with egg': {'calories': 157,
  'fats': 9.4,
  'proteins': 1.96,
  'carbohydrates': 16.18},
 'Mushrooms, raw, white': {'calories': 22,
  'fats': 0.3,
  'proteins': 3.09,
  'carbohydrates': 3.26},
 'Mushrooms, raw, morel': {'calories': 31,
  'fats': 0.6,
  'proteins': 3.12,
  'carbohydrates': 5.1},
 'Cheese, Mexican blend': {'calories': 358,
  'fats': 29.0,
  'proteins': 23.54,
  'carbohydrates': 1.75},
 'Oranges, Florida, raw': {'calories': 46,
  'fats': 0.2,
  'proteins': 0.7,
  'carbohydrates': 11.54},
 'SILK Vanilla, soymilk': {'calories': 41,
  'fats': 1.4,
  'proteins': 2.47,
  'carbohydrates': 4.12},
 'Papaya nectar, canned': {'calories': 57,
  'fats': 0.2,
  'proteins': 0.17,
  'carbohydrates': 14.51},
 'Fiddlehead ferns, raw': {'calories': 34,
  'fats': 0.4,
  'proteins': 4.55,
  'carbohydrates': 5.54},
 'SILK Peach soy yogurt': {'calories': 94,
  'fats': 1.2,
  'proteins': 2.35,
  'carbohydrates': 18.82},
 'SILK Plain soy yogurt': {'calories': 66,
  'fats': 1.8,
  'proteins': 2.64,
  'carbohydrates': 9.69},
 'PACE, Enchilada Sauce': {'calories': 40,
  'fats': 0.0,
  'proteins': 1.67,
  'carbohydrates': 8.33},
 'Yeast extract spread': {'calories': 185,
  'fats': 0.9,
  'proteins': 23.88,
  'carbohydrates': 20.42},
 'Tomatoes, raw, green': {'calories': 23,
  'fats': 0.2,
  'proteins': 1.2,
  'carbohydrates': 5.1},
 'Mollusks, raw, snail': {'calories': 90,
  'fats': 1.4,
  'proteins': 16.1,
  'carbohydrates': 2.0},
 'Emu, raw, fan fillet': {'calories': 103,
  'fats': 0.8,
  'proteins': 22.5,
  'carbohydrates': 0.0},
 'Pasta, enriched, dry': {'calories': 371,
  'fats': 1.5,
  'proteins': 13.04,
  'carbohydrates': 74.67},
 'Cookies, gingersnaps': {'calories': 416,
  'fats': 9.8,
  'proteins': 5.6,
  'carbohydrates': 76.9},
 'Sour cream, fat free': {'calories': 74,
  'fats': 0.0,
  'proteins': 3.1,
  'carbohydrates': 15.6},
 'MURRAY, Honey Graham': {'calories': 445,
  'fats': 13.0,
  'proteins': 5.9,
  'carbohydrates': 75.7},
 'Frankfurter, chicken': {'calories': 223,
  'fats': 16.0,
  'proteins': 15.51,
  'carbohydrates': 2.74},
 'Ham, canned, chopped': {'calories': 239,
  'fats': 19.0,
  'proteins': 16.06,
  'carbohydrates': 0.26},
 'Spices, dried, thyme': {'calories': 276,
  'fats': 7.4,
  'proteins': 9.11,
  'carbohydrates': 63.94},
 'Carrot juice, canned': {'calories': 40,
  'fats': 0.2,
  'proteins': 0.95,
  'carbohydrates': 9.28},
 'Corn, dried (Navajo)': {'calories': 386,
  'fats': 5.2,
  'proteins': 9.88,
  'carbohydrates': 74.93},
 'Pate, truffle flavor': {'calories': 327,
  'fats': 29.0,
  'proteins': 11.2,
  'carbohydrates': 6.3},
 'Fruit butters, apple': {'calories': 173,
  'fats': 0.3,
  'proteins': 0.39,
  'carbohydrates': 42.47},
 'Fast foods, coleslaw': {'calories': 153,
  'fats': 9.9,
  'proteins': 0.95,
  'carbohydrates': 14.89},
 'Salami, beef, cooked': {'calories': 261,
  'fats': 22.0,
  'proteins': 12.6,
  'carbohydrates': 1.9},
 'Spices, chili powder': {'calories': 282,
  'fats': 14.0,
  'proteins': 13.46,
  'carbohydrates': 49.7},
 'Spices, caraway seed': {'calories': 333,
  'fats': 15.0,
  'proteins': 19.77,
  'carbohydrates': 49.9},
 'Spices, dried, basil': {'calories': 233,
  'fats': 4.1,
  'proteins': 22.98,
  'carbohydrates': 47.75},
 'Pickle relish, sweet': {'calories': 130,
  'fats': 0.5,
  'proteins': 0.37,
  'carbohydrates': 35.06},
 'Chives, freeze-dried': {'calories': 311,
  'fats': 3.5,
  'proteins': 21.2,
  'carbohydrates': 64.29},
 'Fish, raw, sablefish': {'calories': 195,
  'fats': 15.0,
  'proteins': 13.41,
  'carbohydrates': 0.0},
 'Crackers, multigrain': {'calories': 482,
  'fats': 20.0,
  'proteins': 7.1,
  'carbohydrates': 67.6},
 'Spices, ground, mace': {'calories': 475,
  'fats': 32.0,
  'proteins': 6.71,
  'carbohydrates': 50.5},
 'Spices, onion powder': {'calories': 341,
  'fats': 1.0,
  'proteins': 10.41,
  'carbohydrates': 79.12},
 'Butter, without salt': {'calories': 717,
  'fats': 81.0,
  'proteins': 0.85,
  'carbohydrates': 0.06},
 'Rice noodles, cooked': {'calories': 108,
  'fats': 0.2,
  'proteins': 1.79,
  'carbohydrates': 24.01},
 'Barley flour or meal': {'calories': 345,
  'fats': 1.6,
  'proteins': 10.5,
  'carbohydrates': 74.52},
 'Sesbania flower, raw': {'calories': 27,
  'fats': 0.0,
  'proteins': 1.28,
  'carbohydrates': 6.73},
 'Garlic bread, frozen': {'calories': 350,
  'fats': 17.0,
  'proteins': 8.36,
  'carbohydrates': 41.72},
 'KFC, Popcorn Chicken': {'calories': 351,
  'fats': 22.0,
  'proteins': 17.67,
  'carbohydrates': 21.18},
 "APPLEBEE'S, coleslaw": {'calories': 120,
  'fats': 7.1,
  'proteins': 0.79,
  'carbohydrates': 13.17},
 'Rolls, sweet, dinner': {'calories': 321,
  'fats': 7.4,
  'proteins': 10.04,
  'carbohydrates': 53.58},
 'Cherries, raw, sweet': {'calories': 63,
  'fats': 0.2,
  'proteins': 1.06,
  'carbohydrates': 16.01},
 'Ostrich, raw, ground': {'calories': 165,
  'fats': 8.7,
  'proteins': 20.22,
  'carbohydrates': 0.0},
 'SILK Coffee, soymilk': {'calories': 62,
  'fats': 1.4,
  'proteins': 2.06,
  'carbohydrates': 10.29},
 'Snacks, banana chips': {'calories': 519,
  'fats': 34.0,
  'proteins': 2.3,
  'carbohydrates': 58.4},
 'Peaches, raw, yellow': {'calories': 39,
  'fats': 0.3,
  'proteins': 0.91,
  'carbohydrates': 9.54},
 'Rolls, wheat, dinner': {'calories': 273,
  'fats': 6.3,
  'proteins': 8.6,
  'carbohydrates': 46.0},
 'Candies, HEATH BITES': {'calories': 530,
  'fats': 30.0,
  'proteins': 3.94,
  'carbohydrates': 63.39},
 'Chicken, raw, ground': {'calories': 143,
  'fats': 8.1,
  'proteins': 17.44,
  'carbohydrates': 0.04},
 'Pears, bartlett, raw': {'calories': 63,
  'fats': 0.2,
  'proteins': 0.39,
  'carbohydrates': 15.01},
 'Toppings, strawberry': {'calories': 254,
  'fats': 0.1,
  'proteins': 0.2,
  'carbohydrates': 66.3},
 'KEEBLER, Sugar Cones': {'calories': 375,
  'fats': 3.7,
  'proteins': 7.3,
  'carbohydrates': 78.0},
 'Seaweed, raw, wakame': {'calories': 45,
  'fats': 0.6,
  'proteins': 3.03,
  'carbohydrates': 9.14},
 'Seaweed, dried, agar': {'calories': 306,
  'fats': 0.3,
  'proteins': 6.21,
  'carbohydrates': 80.88},
 'Bread, cracked-wheat': {'calories': 260,
  'fats': 3.9,
  'proteins': 8.7,
  'carbohydrates': 49.5},
 'Amaranth leaves, raw': {'calories': 23,
  'fats': 0.3,
  'proteins': 2.46,
  'carbohydrates': 4.02},
 'Barley, raw, pearled': {'calories': 352,
  'fats': 1.2,
  'proteins': 9.91,
  'carbohydrates': 77.72},
 'Polish sausage, pork': {'calories': 326,
  'fats': 29.0,
  'proteins': 14.1,
  'carbohydrates': 1.63},
 'Spices, curry powder': {'calories': 325,
  'fats': 14.0,
  'proteins': 14.29,
  'carbohydrates': 55.83},
 'Bacon bits, meatless': {'calories': 476,
  'fats': 26.0,
  'proteins': 32.0,
  'carbohydrates': 28.6},
 'Semolina, unenriched': {'calories': 360,
  'fats': 1.1,
  'proteins': 12.68,
  'carbohydrates': 72.83},
 'Grape leaves, canned': {'calories': 69,
  'fats': 2.0,
  'proteins': 4.27,
  'carbohydrates': 11.71},
 'Spices, ground, sage': {'calories': 315,
  'fats': 13.0,
  'proteins': 10.63,
  'carbohydrates': 60.73},
 'PACE, Red Taco Sauce': {'calories': 50,
  'fats': 0.0,
  'proteins': 0.0,
  'carbohydrates': 12.5},
 "DENNY'S, hash browns": {'calories': 197,
  'fats': 9.0,
  'proteins': 2.49,
  'carbohydrates': 26.59},
 "DENNY'S, onion rings": {'calories': 385,
  'fats': 22.0,
  'proteins': 5.29,
  'carbohydrates': 41.05},