In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('nutrition.csv')

In [3]:
df.head()

,Unnamed: 0,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [4]:
data = df[['name', 'calories', 'total_fat', 'protein', 'carbohydrate']]

In [5]:
data = pd.DataFrame()
data['name'] = df['name'].str.lower()
data['calories'] = df['calories'].astype(int)
data['fats'] = df['total_fat'].str.replace(r'[^\d.]', '', regex=True).astype(float)
data['proteins'] = df['protein'].str.replace(r'[^\d.]', '', regex=True).astype(float)
data['carbohydrates'] = df['carbohydrate'].str.replace(r'[^\d.]', '', regex=True).astype(float)

In [6]:
data.head()

              name  calories  fats  proteins  carbohydrates
0       cornstarch       381   0.1      0.26          91.27
1     nuts, pecans       691  72.0      9.17          13.86
2    eggplant, raw        25   0.2      0.98           5.88
3   teff, uncooked       367   2.4     13.30          73.13
4  sherbet, orange       144   2.0      1.10          30.40

In [7]:
 data['name']=data['name'].str.lower()

In [8]:
dataset = data.set_index('name')

In [16]:
import pandas as pd
from sqlalchemy import create_engine, text, inspect

In [13]:
db_url = "sqlite:///./meal_mentor.db"

In [14]:
engine = create_engine(db_url)

In [17]:
inspector = inspect(engine)

In [18]:
inspector.get_table_names()

['meal_logs', 'users']

In [21]:
# 2. Выполнение запроса и вывод в Pandas
query = "SELECT * FROM meal_logs"

# Способ А: read_sql_query (рекомендуется для SQL-запросов)
with engine.connect() as connection:
    df = pd.read_sql_query(str(query), connection)

/var/folders/kq/dmy4ffs56xj_0h72qcbpyf400000gn/T/ipykernel_84676/340016518.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(str(query), connection)

AttributeError: 'Connection' object has no attribute 'cursor'