In [1]:
import sqlite3

In [3]:
import pandas as pd

In [2]:
df = pd.read_csv('nutrition.csv')

In [3]:
df.head()

,Unnamed: 0,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [4]:
data = df[['name', 'calories', 'total_fat', 'protein', 'carbohydrate']]

In [5]:
data = pd.DataFrame()
data['name'] = df['name'].str.lower()
data['calories'] = df['calories'].astype(int)
data['fats'] = df['total_fat'].str.replace(r'[^\d.]', '', regex=True).astype(float)
data['proteins'] = df['protein'].str.replace(r'[^\d.]', '', regex=True).astype(float)
data['carbohydrates'] = df['carbohydrate'].str.replace(r'[^\d.]', '', regex=True).astype(float)

In [6]:
data.head()

              name  calories  fats  proteins  carbohydrates
0       cornstarch       381   0.1      0.26          91.27
1     nuts, pecans       691  72.0      9.17          13.86
2    eggplant, raw        25   0.2      0.98           5.88
3   teff, uncooked       367   2.4     13.30          73.13
4  sherbet, orange       144   2.0      1.10          30.40

In [7]:
 data['name']=data['name'].str.lower()

In [8]:
dataset = data.set_index('name')

In [32]:
import pandas as pd
import sqlalchemy as sa

db_url = "sqlite:///./meal_mentor.db"
engine = sa.create_engine(db_url)
inspector = sa.inspect(engine)

In [33]:
tables = inspector.get_table_names()
tables

['meal_logs', 'users']

In [37]:
meal_logs = tables[0]  
users = tables[1]  

meals_columns = inspector.get_columns(meal_logs)
users_columns = inspector.get_columns(users)
print('MEALS')
for col in meals_columns:
    print(col['name'], col['type'])
print('USERS')
for col in users_columns:
    print(col['name'], col['type'])

MEALS
id INTEGER
user_id INTEGER
telegram_file_id VARCHAR(255)
ingredients_json TEXT
nutrition_json TEXT
created_at DATETIME
USERS
id INTEGER
telegram_id INTEGER
username VARCHAR(255)
created_at DATETIME

In [31]:

print("pandas:", pd.__version__)
print("sqlalchemy:", sa.__version__)

pandas: 2.2.0
sqlalchemy: 1.4.54

In [4]:

conn = sqlite3.connect("meal_mentor.db")
df_users = pd.read_sql_query("SELECT * FROM users LIMIT 10", conn)
df_users

   id  telegram_id  username                  created_at
0   1    316257868  KritBong  2026-03-11 15:48:56.116994

In [5]:
df_meals = pd.read_sql_query("SELECT * FROM meal_logs LIMIT 10", conn)

df_meals

,id,user_id,telegram_file_id,ingredients_json,nutrition_json,created_at
0,1,1,AgACAgIAAxkBAAMGabGM05vt9goI_9IYbCv8m1ebkJMAAr...,"{""eggs"": 100, ""beans"": 150, ""cheese"": 50}","{""calories"": 220, ""proteins"": 12, ""fats"": 14, ...",2026-03-11 15:48:56.119273
1,2,1,AgACAgIAAxkBAAMDabGK9i7Ze7etUnwqKCa-dbQ83xYAAq...,"{""lettuce"": 50, ""tomato"": 30, ""onion"": 20, ""pa...","{""calories"": 655, ""proteins"": 42, ""fats"": 5, ""...",2026-03-11 15:52:40.369384
2,3,1,AgACAgIAAxkBAAMTabGP8qlrIc7xWvmo_uh1bpTfs7MAAt...,{},{},2026-03-11 15:53:32.964686
3,4,1,AgACAgIAAxkBAAMaabpe-MVbZ6hlO2jL2aq6gOOoZ4cAAp...,"{""arugula"": 50, ""cherry tomatoes"": 60, ""feta c...","{""calories"": 134, ""proteins"": 4, ""fats"": 6, ""c...",2026-03-18 08:24:03.901909